### ISSUE TITLE
the mosesdecoder and subword-nmt is empty

### ISSUE THREAD

**Issue by duterscmy** [e-bug/pascal#1]
when I run prepare_data.sh, problems come out. 
**pascal/tools/mosesdecoder/scripts/tokenizer/tokenizer.perl: No such file or directory**
Then I check and find the program doesn't include these files.
Could you offer these file? thanks very much.

**Comment by duterscmy** [comment]
https://github.com/moses-smt/mosesdecoder

**Comment by duterscmy** [comment]
https://github.com/rsennrich/subword-nmt

**Comment by e-bug** [comment]
Thanks for opening this issue!
I've fixed the submodules. You can now clone this repository with the same versions of the submodules that I used by: 
`git clone --recurse-submodules git@github.com:e-bug/pascal`
