### ISSUE TITLE
 I have a question about the vector p of paper,

### ISSUE THREAD

**Issue by xinsheng44** [e-bug/pascal#3]
Hello, I have a question about the vector p of paper, how does a sentence get the dependency relationship of its parents? Is this arrow pointing artificially labeled?
![图片](https://user-images.githubusercontent.com/59272013/99878479-9b4d5e00-2c40-11eb-9e84-78daa58c8dda.png)

**Comment by e-bug** [comment]
We use a parser (e.g. [CoreNLP](https://stanfordnlp.github.io/CoreNLP/)) to annotate each sentence with its dependency tree.

When the parent is split into multiple subwords, we use its middle position as described in the paper.
Code to do this is [here](https://github.com/e-bug/pascal/blob/master/scripts/bpe_tags_mean.py).
